---
- name: Install packages
  apt: name={{ item }} state=latest
  with_items:
    - supervisor
    - netcat-openbsd

- name: Create configuration directories
  file: path=/etc/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - bootils
    - bootils/nanny.d

- name: Install global configuration file if absent
  copy: src="etc/{{ item.name }}" dest="/etc/bootils/{{ item.name }}" owner=root group=root mode=0644 force="{{ item.force }}"
  with_items:
    - { name: nanny.conf, force: no }
    - { name: nanny.d/netcat.conf, force: yes }
