---
- name: Install packages
  apt: name={{ item }} state=latest
  with_items:
    - supervisor
    - netcat-openbsd

- name: Create configuration directory
  file: path=/etc/bootils state=directory owner=root group=root mode=0755

- name: Install configuration files
  copy: src=etc/{{ item }} dest=/etc/bootils/{{ item }} owner=root group=root mode=0644
  with_items:
    - nanny.conf
